.PHONY: dev build build-release test lint fmt fmt-check migrate pre-commit validate clean help


.DEFAULT_GOAL := help

dev build build-release test lint fmt fmt-check migrate pre-commit validate clean help:
	@node makefile.mjs $@
