export type ThemeOption = {
  name: string;
  category: string;
  background: string;
  foreground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  border: string;
  cardBg: string;
  cardForeground: string;
  mutedForeground: string;
  accentForeground: string;
  popoverForeground: string;
};

export const themes: ThemeOption[] = [
  {
    name: "Midnight Blue",
    category: "Professional Dark",
    background: "#0f1218",
    foreground: "#e2e8f0",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1e293b",
    secondaryForeground: "#e2e8f0",
    border: "#1e293b",
    cardBg: "#171c24",
    cardForeground: "#e2e8f0",
    mutedForeground: "#94a3b8",
    accentForeground: "#e2e8f0",
    popoverForeground: "#e2e8f0",
  },
  {
    name: "Deep Space",
    category: "Cosmic",
    background: "#10101e",
    foreground: "#e2e8f0",
    primary: "#8b5cf6",
    primaryForeground: "#ffffff",
    secondary: "#1e1e2d",
    secondaryForeground: "#e2e8f0",
    border: "#1e1e2d",
    cardBg: "#16162c",
    cardForeground: "#e2e8f0",
    mutedForeground: "#a8a8b8",
    accentForeground: "#e2e8f0",
    popoverForeground: "#e2e8f0",
  },
  {
    name: "Dark Charcoal",
    category: "Minimal Dark",
    background: "#121212",
    foreground: "#e2e8f0",
    primary: "#64748b",
    primaryForeground: "#ffffff",
    secondary: "#1f1f1f",
    secondaryForeground: "#e2e8f0",
    border: "#252525",
    cardBg: "#1a1a1a",
    cardForeground: "#e2e8f0",
    mutedForeground: "#94a3b8",
    accentForeground: "#e2e8f0",
    popoverForeground: "#e2e8f0",
  },
  {
    name: "Obsidian",
    category: "Minimal Dark",
    background: "#0f0f0f",
    foreground: "#d4d4d8",
    primary: "#22c55e",
    primaryForeground: "#000000",
    secondary: "#1c1c1c",
    secondaryForeground: "#d4d4d8",
    border: "#262626",
    cardBg: "#171717",
    cardForeground: "#d4d4d8",
    mutedForeground: "#a1a1aa",
    accentForeground: "#d4d4d8",
    popoverForeground: "#d4d4d8",
  },
  {
    name: "Stealth",
    category: "Professional Dark",
    background: "#131313",
    foreground: "#e5e5e5",
    primary: "#60a5fa",
    primaryForeground: "#ffffff",
    secondary: "#202020",
    secondaryForeground: "#e5e5e5",
    border: "#2a2a2a",
    cardBg: "#1c1c1c",
    cardForeground: "#e5e5e5",
    mutedForeground: "#a3a3a3",
    accentForeground: "#e5e5e5",
    popoverForeground: "#e5e5e5",
  },
  {
    name: "Deep Forest",
    category: "Nature",
    background: "#0c130d",
    foreground: "#d5e8d8",
    primary: "#059669",
    primaryForeground: "#ffffff",
    secondary: "#152116",
    secondaryForeground: "#d5e8d8",
    border: "#1c2c1f",
    cardBg: "#111914",
    cardForeground: "#d5e8d8",
    mutedForeground: "#a8c9ab",
    accentForeground: "#d5e8d8",
    popoverForeground: "#d5e8d8",
  },
  {
    name: "Simple Dark",
    category: "Minimal Dark",
    background: "#121212",
    foreground: "#ffffff",
    primary: "#4f46e5",
    primaryForeground: "#ffffff",
    secondary: "#1e1e1e",
    secondaryForeground: "#ffffff",
    border: "#303030",
    cardBg: "#1e1e1e",
    cardForeground: "#ffffff",
    mutedForeground: "#b3b3b3",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
  },
  {
    name: "Monochrome",
    category: "High Contrast",
    background: "#0a0a0a",
    foreground: "#e0e0e0",
    primary: "#a3a3a3",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#e0e0e0",
    border: "#262626",
    cardBg: "#141414",
    cardForeground: "#e0e0e0",
    mutedForeground: "#8a8a8a",
    accentForeground: "#e0e0e0",
    popoverForeground: "#e0e0e0",
  },
  {
    name: "Midnight Zen",
    category: "Zen & Focus",
    background: "#121923",
    foreground: "#e2e7ef",
    primary: "#a599e9",
    primaryForeground: "#1a1625",
    secondary: "#1e2736",
    secondaryForeground: "#e2e7ef",
    border: "#2a3343",
    cardBg: "#1a212e",
    cardForeground: "#e2e7ef",
    mutedForeground: "#9ba3b5",
    accentForeground: "#e2e7ef",
    popoverForeground: "#e2e7ef",
  },
  {
    name: "Forest Dark",
    category: "Nature",
    background: "#131a17",
    foreground: "#e0e9e4",
    primary: "#7eb8a0",
    primaryForeground: "#0d1812",
    secondary: "#1a2522",
    secondaryForeground: "#e0e9e4",
    border: "#263330",
    cardBg: "#19221f",
    cardForeground: "#e0e9e4",
    mutedForeground: "#a5c0b1",
    accentForeground: "#e0e9e4",
    popoverForeground: "#e0e9e4",
  },
  {
    name: "Mocha",
    category: "Warm & Cozy",
    background: "#1a1614",
    foreground: "#e8e1d9",
    primary: "#d3a976",
    primaryForeground: "#1a1614",
    secondary: "#272220",
    secondaryForeground: "#e8e1d9",
    border: "#332e2a",
    cardBg: "#221e1b",
    cardForeground: "#e8e1d9",
    mutedForeground: "#c4b8a8",
    accentForeground: "#e8e1d9",
    popoverForeground: "#e8e1d9",
  },
  {
    name: "Graphite",
    category: "Professional Dark",
    background: "#131517",
    foreground: "#e2e4e8",
    primary: "#8ab4d8",
    primaryForeground: "#0a0c0e",
    secondary: "#1d2024",
    secondaryForeground: "#e2e4e8",
    border: "#282c33",
    cardBg: "#1b1e22",
    cardForeground: "#e2e4e8",
    mutedForeground: "#a8adb5",
    accentForeground: "#e2e4e8",
    popoverForeground: "#e2e4e8",
  },
  {
    name: "Twilight",
    category: "Artistic",
    background: "#15131e",
    foreground: "#e4e2ec",
    primary: "#f0a387",
    primaryForeground: "#2c1f1a",
    secondary: "#211e2c",
    secondaryForeground: "#e4e2ec",
    border: "#2c293a",
    cardBg: "#1c1a27",
    cardForeground: "#e4e2ec",
    mutedForeground: "#b5b0c4",
    accentForeground: "#e4e2ec",
    popoverForeground: "#e4e2ec",
  },
  {
    name: "Oceanic",
    category: "Nature",
    background: "#0e1b1f",
    foreground: "#dde7e9",
    primary: "#65b6c2",
    primaryForeground: "#082a32",
    secondary: "#162b30",
    secondaryForeground: "#dde7e9",
    border: "#20373d",
    cardBg: "#132428",
    cardForeground: "#dde7e9",
    mutedForeground: "#9bb9c2",
    accentForeground: "#dde7e9",
    popoverForeground: "#dde7e9",
  },
  {
    name: "Dark Sepia",
    category: "Warm & Cozy",
    background: "#191715",
    foreground: "#e5e0d7",
    primary: "#c2966a",
    primaryForeground: "#1a1714",
    secondary: "#252220",
    secondaryForeground: "#e5e0d7",
    border: "#32302d",
    cardBg: "#201e1b",
    cardForeground: "#e5e0d7",
    mutedForeground: "#b8b0a4",
    accentForeground: "#e5e0d7",
    popoverForeground: "#e5e0d7",
  },
  {
    name: "Amber Glow",
    category: "Neon & Glow",
    background: "#0e0d0c",
    foreground: "#f3f0e9",
    primary: "#ff9e64",
    primaryForeground: "#1a1511",
    secondary: "#1a1815",
    secondaryForeground: "#f3f0e9",
    border: "#2a2620",
    cardBg: "#14120f",
    cardForeground: "#f3f0e9",
    mutedForeground: "#d4c5a8",
    accentForeground: "#f3f0e9",
    popoverForeground: "#f3f0e9",
  },
  {
    name: "Synthwave Sunset",
    category: "Retro & Synthwave",
    background: "#100720",
    foreground: "#eee6f5",
    primary: "#fc61ff",
    primaryForeground: "#1a0428",
    secondary: "#1d0c32",
    secondaryForeground: "#eee6f5",
    border: "#2d1445",
    cardBg: "#150b2a",
    cardForeground: "#eee6f5",
    mutedForeground: "#c8b5d9",
    accentForeground: "#eee6f5",
    popoverForeground: "#eee6f5",
  },
  {
    name: "Glacier Blue",
    category: "Cool & Crisp",
    background: "#0c1419",
    foreground: "#e8eff3",
    primary: "#5ccfe6",
    primaryForeground: "#082a35",
    secondary: "#152126",
    secondaryForeground: "#e8eff3",
    border: "#1e2c35",
    cardBg: "#10191f",
    cardForeground: "#e8eff3",
    mutedForeground: "#b4c8d1",
    accentForeground: "#e8eff3",
    popoverForeground: "#e8eff3",
  },
  {
    name: "Neo Tokyo",
    category: "Retro & Synthwave",
    background: "#0f0a0c",
    foreground: "#f0e3e6",
    primary: "#ff3d5e",
    primaryForeground: "#ffffff",
    secondary: "#1a1115",
    secondaryForeground: "#f0e3e6",
    border: "#2a1a20",
    cardBg: "#150e11",
    cardForeground: "#f0e3e6",
    mutedForeground: "#d4b8be",
    accentForeground: "#f0e3e6",
    popoverForeground: "#f0e3e6",
  },
  {
    name: "Emerald Depth",
    category: "Nature",
    background: "#0b1512",
    foreground: "#e5efed",
    primary: "#26c281",
    primaryForeground: "#ffffff",
    secondary: "#122018",
    secondaryForeground: "#e5efed",
    border: "#1c3129",
    cardBg: "#0f1b17",
    cardForeground: "#e5efed",
    mutedForeground: "#a8c9ba",
    accentForeground: "#e5efed",
    popoverForeground: "#e5efed",
  },
  {
    name: "Cyberpunk Night",
    category: "Gaming & Futuristic",
    background: "#0d0d15",
    foreground: "#eeeef9",
    primary: "#ff7edb",
    primaryForeground: "#1a0d18",
    secondary: "#18181f",
    secondaryForeground: "#eeeef9",
    border: "#28282f",
    cardBg: "#13131a",
    cardForeground: "#eeeef9",
    mutedForeground: "#c4c4d9",
    accentForeground: "#eeeef9",
    popoverForeground: "#eeeef9",
  },
  {
    name: "Cosmic Void",
    category: "Cosmic",
    background: "#070b14",
    foreground: "#dfecfd",
    primary: "#4dadff",
    primaryForeground: "#ffffff",
    secondary: "#101420",
    secondaryForeground: "#dfecfd",
    border: "#212940",
    cardBg: "#0c1018",
    cardForeground: "#dfecfd",
    mutedForeground: "#a8c1e8",
    accentForeground: "#dfecfd",
    popoverForeground: "#dfecfd",
  },
  {
    name: "Aurora Borealis",
    category: "Cosmic",
    background: "#0a0e17",
    foreground: "#e2eaf2",
    primary: "#64d9ef",
    primaryForeground: "#041218",
    secondary: "#121a29",
    secondaryForeground: "#e2eaf2",
    border: "#1e2738",
    cardBg: "#131824",
    cardForeground: "#e2eaf2",
    mutedForeground: "#a8c1d1",
    accentForeground: "#e2eaf2",
    popoverForeground: "#e2eaf2",
  },
  {
    name: "Matrix Code",
    category: "Developer",
    background: "#0d0d0d",
    foreground: "#dbfcdb",
    primary: "#00ff41",
    primaryForeground: "#000000",
    secondary: "#151515",
    secondaryForeground: "#dbfcdb",
    border: "#252525",
    cardBg: "#111111",
    cardForeground: "#dbfcdb",
    mutedForeground: "#9dd99d",
    accentForeground: "#dbfcdb",
    popoverForeground: "#dbfcdb",
  },
  {
    name: "Lavender Dreams",
    category: "Artistic",
    background: "#191627",
    foreground: "#f0ebfa",
    primary: "#b388ff",
    primaryForeground: "#1a0d2e",
    secondary: "#252236",
    secondaryForeground: "#f0ebfa",
    border: "#342f4a",
    cardBg: "#1e1a2e",
    cardForeground: "#f0ebfa",
    mutedForeground: "#c4b5d9",
    accentForeground: "#f0ebfa",
    popoverForeground: "#f0ebfa",
  },
  {
    name: "Python Zen",
    category: "Developer",
    background: "#1a212e",
    foreground: "#e5e9f0",
    primary: "#5e81ac",
    primaryForeground: "#ffffff",
    secondary: "#232c3b",
    secondaryForeground: "#e5e9f0",
    border: "#3b4252",
    cardBg: "#1f2937",
    cardForeground: "#e5e9f0",
    mutedForeground: "#94a3b8",
    accentForeground: "#e5e9f0",
    popoverForeground: "#e5e9f0",
  },
  {
    name: "Go Blue",
    category: "Developer",
    background: "#0e1621",
    foreground: "#e8eaed",
    primary: "#00ADD8",
    primaryForeground: "#ffffff",
    secondary: "#172533",
    secondaryForeground: "#e8eaed",
    border: "#253443",
    cardBg: "#131e2c",
    cardForeground: "#e8eaed",
    mutedForeground: "#a8bcc8",
    accentForeground: "#e8eaed",
    popoverForeground: "#e8eaed",
  },
  {
    name: "GitHub Dark",
    category: "Developer",
    background: "#0d1117",
    foreground: "#c9d1d9",
    primary: "#58a6ff",
    primaryForeground: "#ffffff",
    secondary: "#161b22",
    secondaryForeground: "#c9d1d9",
    border: "#30363d",
    cardBg: "#1c2128",
    cardForeground: "#c9d1d9",
    mutedForeground: "#8b949e",
    accentForeground: "#c9d1d9",
    popoverForeground: "#c9d1d9",
  },
  {
    name: "Rust Orange",
    category: "Developer",
    background: "#161616",
    foreground: "#eeeeee",
    primary: "#f74c00",
    primaryForeground: "#ffffff",
    secondary: "#202020",
    secondaryForeground: "#eeeeee",
    border: "#333333",
    cardBg: "#1a1a1a",
    cardForeground: "#eeeeee",
    mutedForeground: "#cccccc",
    accentForeground: "#eeeeee",
    popoverForeground: "#eeeeee",
  },
  {
    name: "VSCode Night",
    category: "Developer",
    background: "#1e1e1e",
    foreground: "#d4d4d4",
    primary: "#569cd6",
    primaryForeground: "#ffffff",
    secondary: "#252526",
    secondaryForeground: "#d4d4d4",
    border: "#333333",
    cardBg: "#2d2d2d",
    cardForeground: "#d4d4d4",
    mutedForeground: "#a0a0a0",
    accentForeground: "#d4d4d4",
    popoverForeground: "#d4d4d4",
  },
  {
    name: "Terminal Green",
    category: "Developer",
    background: "#0c0c0c",
    foreground: "#e0e0e0",
    primary: "#4af626",
    primaryForeground: "#000000",
    secondary: "#181818",
    secondaryForeground: "#e0e0e0",
    border: "#2a2a2a",
    cardBg: "#141414",
    cardForeground: "#e0e0e0",
    mutedForeground: "#a8a8a8",
    accentForeground: "#e0e0e0",
    popoverForeground: "#e0e0e0",
  },
  {
    name: "Syntax Highlight",
    category: "Developer",
    background: "#1e1e1e",
    foreground: "#f8f8f2",
    primary: "#ff79c6",
    primaryForeground: "#1e1e1e",
    secondary: "#282a36",
    secondaryForeground: "#f8f8f2",
    border: "#44475a",
    cardBg: "#21222c",
    cardForeground: "#f8f8f2",
    mutedForeground: "#9ca0a8",
    accentForeground: "#f8f8f2",
    popoverForeground: "#f8f8f2",
  },
  {
    name: "Ocean Breeze",
    category: "Nature",
    background: "#0e1c22",
    foreground: "#edf4f7",
    primary: "#64b5cd",
    primaryForeground: "#041015",
    secondary: "#172930",
    secondaryForeground: "#edf4f7",
    border: "#233841",
    cardBg: "#121f26",
    cardForeground: "#edf4f7",
    mutedForeground: "#b8d1db",
    accentForeground: "#edf4f7",
    popoverForeground: "#edf4f7",
  },
  {
    name: "Midnight Plum",
    category: "Artistic",
    background: "#141319",
    foreground: "#f5f1f8",
    primary: "#9c77b8",
    primaryForeground: "#ffffff",
    secondary: "#1e1c23",
    secondaryForeground: "#f5f1f8",
    border: "#2d2a34",
    cardBg: "#19171e",
    cardForeground: "#f5f1f8",
    mutedForeground: "#c8b8d4",
    accentForeground: "#f5f1f8",
    popoverForeground: "#f5f1f8",
  },
  {
    name: "Succulent Garden",
    category: "Nature",
    background: "#1a211d",
    foreground: "#f0f5f3",
    primary: "#7acca6",
    primaryForeground: "#0d1611",
    secondary: "#242c28",
    secondaryForeground: "#f0f5f3",
    border: "#353f3a",
    cardBg: "#1f2723",
    cardForeground: "#f0f5f3",
    mutedForeground: "#b8d1c8",
    accentForeground: "#f0f5f3",
    popoverForeground: "#f0f5f3",
  },
  {
    name: "Cherry Blossom",
    category: "Artistic",
    background: "#1a1520",
    foreground: "#f8eef3",
    primary: "#f0a9b8",
    primaryForeground: "#2a1826",
    secondary: "#261e2a",
    secondaryForeground: "#f8eef3",
    border: "#3a2d3e",
    cardBg: "#211a26",
    cardForeground: "#f8eef3",
    mutedForeground: "#d4b8c8",
    accentForeground: "#f8eef3",
    popoverForeground: "#f8eef3",
  },
  {
    name: "Peacock Feather",
    category: "Nature",
    background: "#0d192b",
    foreground: "#f1f6fc",
    primary: "#45b7cd",
    primaryForeground: "#ffffff",
    secondary: "#14263c",
    secondaryForeground: "#f1f6fc",
    border: "#203552",
    cardBg: "#101d32",
    cardForeground: "#f1f6fc",
    mutedForeground: "#b8d1db",
    accentForeground: "#f1f6fc",
    popoverForeground: "#f1f6fc",
  },
  {
    name: "Amethyst Glow",
    category: "Neon & Glow",
    background: "#1e1033",
    foreground: "#f2ebf9",
    primary: "#c792ea",
    primaryForeground: "#1e0d2a",
    secondary: "#2a1746",
    secondaryForeground: "#f2ebf9",
    border: "#3d2361",
    cardBg: "#24133d",
    cardForeground: "#f2ebf9",
    mutedForeground: "#c4b5d9",
    accentForeground: "#f2ebf9",
    popoverForeground: "#f2ebf9",
  },
  {
    name: "Coral Reef",
    category: "Nature",
    background: "#0f2231",
    foreground: "#f0f5f9",
    primary: "#ff8080",
    primaryForeground: "#ffffff",
    secondary: "#16303f",
    secondaryForeground: "#f0f5f9",
    border: "#234758",
    cardBg: "#122736",
    cardForeground: "#f0f5f9",
    mutedForeground: "#b8d1db",
    accentForeground: "#f0f5f9",
    popoverForeground: "#f0f5f9",
  },
  {
    name: "Mint Chocolate",
    category: "Nature",
    background: "#191a19",
    foreground: "#e8f3ef",
    primary: "#4cd6a0",
    primaryForeground: "#0d1811",
    secondary: "#222322",
    secondaryForeground: "#e8f3ef",
    border: "#2f302f",
    cardBg: "#1e1f1e",
    cardForeground: "#e8f3ef",
    mutedForeground: "#a8c9ba",
    accentForeground: "#e8f3ef",
    popoverForeground: "#e8f3ef",
  },
  {
    name: "Rose Gold",
    category: "Warm & Cozy",
    background: "#1a1517",
    foreground: "#f8eef1",
    primary: "#f2c9b5",
    primaryForeground: "#2a1a1d",
    secondary: "#251e20",
    secondaryForeground: "#f8eef1",
    border: "#382f32",
    cardBg: "#211a1c",
    cardForeground: "#f8eef1",
    mutedForeground: "#d4b8c8",
    accentForeground: "#f8eef1",
    popoverForeground: "#f8eef1",
  },
  {
    name: "Classic Light",
    category: "Professional Light",
    background: "#ffffff",
    foreground: "#1f2937",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#f3f4f6",
    secondaryForeground: "#1f2937",
    border: "#e5e7eb",
    cardBg: "#f9fafb",
    cardForeground: "#1f2937",
    mutedForeground: "#6b7280",
    accentForeground: "#1f2937",
    popoverForeground: "#1f2937",
  },
  {
    name: "Soft Gray",
    category: "Minimal Light",
    background: "#f8fafc",
    foreground: "#334155",
    primary: "#6366f1",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#334155",
    border: "#e2e8f0",
    cardBg: "#ffffff",
    cardForeground: "#334155",
    mutedForeground: "#64748b",
    accentForeground: "#334155",
    popoverForeground: "#334155",
  },
  {
    name: "Warm Cream",
    category: "Warm & Cozy",
    background: "#fefbf7",
    foreground: "#44403c",
    primary: "#ea580c",
    primaryForeground: "#ffffff",
    secondary: "#fef7ed",
    secondaryForeground: "#44403c",
    border: "#fed7aa",
    cardBg: "#fffbeb",
    cardForeground: "#44403c",
    mutedForeground: "#78716c",
    accentForeground: "#44403c",
    popoverForeground: "#44403c",
  },
  {
    name: "Fresh Mint",
    category: "Cool & Crisp",
    background: "#f0fdf4",
    foreground: "#14532d",
    primary: "#16a34a",
    primaryForeground: "#ffffff",
    secondary: "#f7fee7",
    secondaryForeground: "#14532d",
    border: "#bbf7d0",
    cardBg: "#ecfdf5",
    cardForeground: "#14532d",
    mutedForeground: "#16a34a",
    accentForeground: "#14532d",
    popoverForeground: "#14532d",
  },
  {
    name: "Ocean Breeze Light",
    category: "Cool & Crisp",
    background: "#f0f9ff",
    foreground: "#0c4a6e",
    primary: "#0ea5e9",
    primaryForeground: "#ffffff",
    secondary: "#e0f2fe",
    secondaryForeground: "#0c4a6e",
    border: "#7dd3fc",
    cardBg: "#f0f9ff",
    cardForeground: "#0c4a6e",
    mutedForeground: "#0369a1",
    accentForeground: "#0c4a6e",
    popoverForeground: "#0c4a6e",
  },
  {
    name: "Lavender Light",
    category: "Pastel & Soft",
    background: "#faf5ff",
    foreground: "#581c87",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#f3e8ff",
    secondaryForeground: "#581c87",
    border: "#c4b5fd",
    cardBg: "#faf5ff",
    cardForeground: "#581c87",
    mutedForeground: "#7c3aed",
    accentForeground: "#581c87",
    popoverForeground: "#581c87",
  },
  {
    name: "Sunrise",
    category: "Energetic & Bright",
    background: "#fff7ed",
    foreground: "#9a3412",
    primary: "#f97316",
    primaryForeground: "#ffffff",
    secondary: "#ffedd5",
    secondaryForeground: "#9a3412",
    border: "#fed7aa",
    cardBg: "#fffbeb",
    cardForeground: "#9a3412",
    mutedForeground: "#c2410c",
    accentForeground: "#9a3412",
    popoverForeground: "#9a3412",
  },
  {
    name: "Cherry Blossom Light",
    category: "Pastel & Soft",
    background: "#fdf2f8",
    foreground: "#831843",
    primary: "#ec4899",
    primaryForeground: "#ffffff",
    secondary: "#fce7f3",
    secondaryForeground: "#831843",
    border: "#f9a8d4",
    cardBg: "#fef7f0",
    cardForeground: "#831843",
    mutedForeground: "#be185d",
    accentForeground: "#831843",
    popoverForeground: "#831843",
  },
  {
    name: "Forest Light",
    category: "Nature",
    background: "#f6fdf9",
    foreground: "#14532d",
    primary: "#059669",
    primaryForeground: "#ffffff",
    secondary: "#ecfdf5",
    secondaryForeground: "#14532d",
    border: "#86efac",
    cardBg: "#f0fdf4",
    cardForeground: "#14532d",
    mutedForeground: "#047857",
    accentForeground: "#14532d",
    popoverForeground: "#14532d",
  },
  {
    name: "Arctic White",
    category: "High Contrast",
    background: "#f8fafc",
    foreground: "#0f172a",
    primary: "#0f766e",
    primaryForeground: "#ffffff",
    secondary: "#f0fdfa",
    secondaryForeground: "#0f172a",
    border: "#5eead4",
    cardBg: "#ffffff",
    cardForeground: "#0f172a",
    mutedForeground: "#0d9488",
    accentForeground: "#0f172a",
    popoverForeground: "#0f172a",
  },
  {
    name: "Peachy Keen",
    category: "Pastel & Soft",
    background: "#fef2f2",
    foreground: "#7f1d1d",
    primary: "#dc2626",
    primaryForeground: "#ffffff",
    secondary: "#fee2e2",
    secondaryForeground: "#7f1d1d",
    border: "#fca5a5",
    cardBg: "#fffbfb",
    cardForeground: "#7f1d1d",
    mutedForeground: "#b91c1c",
    accentForeground: "#7f1d1d",
    popoverForeground: "#7f1d1d",
  },
  {
    name: "Golden Hour",
    category: "Energetic & Bright",
    background: "#fffbeb",
    foreground: "#78350f",
    primary: "#d97706",
    primaryForeground: "#ffffff",
    secondary: "#fef3c7",
    secondaryForeground: "#78350f",
    border: "#fde68a",
    cardBg: "#fffbeb",
    cardForeground: "#78350f",
    mutedForeground: "#a16207",
    accentForeground: "#78350f",
    popoverForeground: "#78350f",
  },
  {
    name: "Paper White",
    category: "Professional Light",
    background: "#ffffff",
    foreground: "#374151",
    primary: "#4f46e5",
    primaryForeground: "#ffffff",
    secondary: "#f9fafb",
    secondaryForeground: "#374151",
    border: "#d1d5db",
    cardBg: "#f3f4f6",
    cardForeground: "#374151",
    mutedForeground: "#6b7280",
    accentForeground: "#374151",
    popoverForeground: "#374151",
  },
  {
    name: "Sage Green",
    category: "Zen & Focus",
    background: "#f6f7f4",
    foreground: "#365314",
    primary: "#65a30d",
    primaryForeground: "#ffffff",
    secondary: "#f7fee7",
    secondaryForeground: "#365314",
    border: "#bef264",
    cardBg: "#fefffe",
    cardForeground: "#365314",
    mutedForeground: "#4d7c0f",
    accentForeground: "#365314",
    popoverForeground: "#365314",
  },
  {
    name: "Powder Blue",
    category: "Cool & Crisp",
    background: "#f0f9ff",
    foreground: "#0c4a6e",
    primary: "#0284c7",
    primaryForeground: "#ffffff",
    secondary: "#e0f2fe",
    secondaryForeground: "#0c4a6e",
    border: "#bae6fd",
    cardBg: "#f8fafc",
    cardForeground: "#0c4a6e",
    mutedForeground: "#0369a1",
    accentForeground: "#0c4a6e",
    popoverForeground: "#0c4a6e",
  },
  {
    name: "Vanilla Cream",
    category: "Warm & Cozy",
    background: "#fffef7",
    foreground: "#451a03",
    primary: "#a16207",
    primaryForeground: "#ffffff",
    secondary: "#fefce8",
    secondaryForeground: "#451a03",
    border: "#fde047",
    cardBg: "#fefdf4",
    cardForeground: "#451a03",
    mutedForeground: "#713f12",
    accentForeground: "#451a03",
    popoverForeground: "#451a03",
  },
  {
    name: "Cotton Candy",
    category: "Pastel & Soft",
    background: "#fdf4ff",
    foreground: "#701a75",
    primary: "#c026d3",
    primaryForeground: "#ffffff",
    secondary: "#fae8ff",
    secondaryForeground: "#701a75",
    border: "#e879f9",
    cardBg: "#fefbff",
    cardForeground: "#701a75",
    mutedForeground: "#a21caf",
    accentForeground: "#701a75",
    popoverForeground: "#701a75",
  },
  {
    name: "Soft Coral",
    category: "Pastel & Soft",
    background: "#fff5f5",
    foreground: "#7c2d12",
    primary: "#f56565",
    primaryForeground: "#ffffff",
    secondary: "#fed7d7",
    secondaryForeground: "#7c2d12",
    border: "#feb2b2",
    cardBg: "#fffafa",
    cardForeground: "#7c2d12",
    mutedForeground: "#dc2626",
    accentForeground: "#7c2d12",
    popoverForeground: "#7c2d12",
  },
  {
    name: "Misty Morning",
    category: "Minimal Light",
    background: "#f1f5f9",
    foreground: "#1e293b",
    primary: "#475569",
    primaryForeground: "#ffffff",
    secondary: "#e2e8f0",
    secondaryForeground: "#1e293b",
    border: "#cbd5e1",
    cardBg: "#f8fafc",
    cardForeground: "#1e293b",
    mutedForeground: "#64748b",
    accentForeground: "#1e293b",
    popoverForeground: "#1e293b",
  },
];

export const themeCategories = [
  {
    name: "Professional Dark",
    icon: "💼",
    description: "Sleek, polished themes for work environments",
  },
  {
    name: "Professional Light",
    icon: "🏢",
    description: "Clean, business-friendly light themes",
  },
  {
    name: "Developer",
    icon: "💻",
    description: "Code-friendly themes inspired by popular editors",
  },
  {
    name: "Minimal Dark",
    icon: "🌚",
    description: "Clean, distraction-free dark themes",
  },
  {
    name: "Minimal Light",
    icon: "⚪",
    description: "Simple, uncluttered light themes",
  },
  {
    name: "Nature",
    icon: "🌿",
    description: "Earth-inspired themes with natural colors",
  },
  {
    name: "Cosmic",
    icon: "🌌",
    description: "Space and galaxy-inspired themes",
  },
  {
    name: "Retro & Synthwave",
    icon: "🕹️",
    description: "80s-inspired neon and retro themes",
  },
  {
    name: "Gaming & Futuristic",
    icon: "🎮",
    description: "Cyberpunk and futuristic gaming themes",
  },
  {
    name: "Artistic",
    icon: "🎨",
    description: "Creative, expressive themes for artists",
  },
  {
    name: "Zen & Focus",
    icon: "🧘",
    description: "Calming themes designed for concentration",
  },
  {
    name: "Warm & Cozy",
    icon: "🔥",
    description: "Comfortable, warm-toned themes",
  },
  {
    name: "Cool & Crisp",
    icon: "❄️",
    description: "Fresh, cool-toned themes",
  },
  {
    name: "Neon & Glow",
    icon: "✨",
    description: "Bright, glowing accent themes",
  },
  {
    name: "Pastel & Soft",
    icon: "🌸",
    description: "Gentle, soft-colored themes",
  },
  {
    name: "Energetic & Bright",
    icon: "⚡",
    description: "Vibrant, energizing themes",
  },
  {
    name: "High Contrast",
    icon: "⚫",
    description: "Bold, high-contrast themes for accessibility",
  },
];
