export type ThemeOption = {
  name: string;
  category: string;
  background: string;
  foreground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  border: string;
  cardBg: string;
  cardForeground: string;
  mutedForeground: string;
  accentForeground: string;
  popoverForeground: string;
  isDark: boolean;
};

export const themes: ThemeOption[] = [
  {
    name: "GitHub Dark",
    category: "Modern Dark",
    background: "#0d1117",
    foreground: "#f0f6fc",
    primary: "#58a6ff",
    primaryForeground: "#ffffff",
    secondary: "#21262d",
    secondaryForeground: "#f0f6fc",
    border: "#30363d",
    cardBg: "#161b22",
    cardForeground: "#f0f6fc",
    mutedForeground: "#8b949e",
    accentForeground: "#f0f6fc",
    popoverForeground: "#f0f6fc",
    isDark: true,
  },
  {
    name: "Linear Dark",
    category: "Modern Dark",
    background: "#0c0d0e",
    foreground: "#ffffff",
    primary: "#5e6ad2",
    primaryForeground: "#ffffff",
    secondary: "#1a1b1e",
    secondaryForeground: "#ffffff",
    border: "#2a2d31",
    cardBg: "#151618",
    cardForeground: "#ffffff",
    mutedForeground: "#9ca3af",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "Notion Dark",
    category: "Modern Dark",
    background: "#191919",
    foreground: "#ffffff",
    primary: "#2eaadc",
    primaryForeground: "#ffffff",
    secondary: "#2f2f2f",
    secondaryForeground: "#ffffff",
    border: "#373737",
    cardBg: "#242424",
    cardForeground: "#ffffff",
    mutedForeground: "#9b9b9b",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "Vercel Dark",
    category: "Modern Dark",
    background: "#000000",
    foreground: "#fafafa",
    primary: "#0070f3",
    primaryForeground: "#ffffff",
    secondary: "#111111",
    secondaryForeground: "#fafafa",
    border: "#333333",
    cardBg: "#111111",
    cardForeground: "#fafafa",
    mutedForeground: "#666666",
    accentForeground: "#fafafa",
    popoverForeground: "#fafafa",
    isDark: true,
  },
  {
    name: "Discord Dark",
    category: "Modern Dark",
    background: "#2c2f33",
    foreground: "#ffffff",
    primary: "#7289da",
    primaryForeground: "#ffffff",
    secondary: "#23272a",
    secondaryForeground: "#ffffff",
    border: "#40444b",
    cardBg: "#36393f",
    cardForeground: "#ffffff",
    mutedForeground: "#b9bbbe",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "Spotify Dark",
    category: "Modern Dark",
    background: "#121212",
    foreground: "#ffffff",
    primary: "#1db954",
    primaryForeground: "#000000",
    secondary: "#181818",
    secondaryForeground: "#ffffff",
    border: "#282828",
    cardBg: "#181818",
    cardForeground: "#ffffff",
    mutedForeground: "#b3b3b3",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "Slack Dark",
    category: "Modern Dark",
    background: "#1a1d21",
    foreground: "#d1d2d3",
    primary: "#1264a3",
    primaryForeground: "#ffffff",
    secondary: "#232529",
    secondaryForeground: "#d1d2d3",
    border: "#2b2e33",
    cardBg: "#1f2225",
    cardForeground: "#d1d2d3",
    mutedForeground: "#ababad",
    accentForeground: "#d1d2d3",
    popoverForeground: "#d1d2d3",
    isDark: true,
  },
  {
    name: "Catppuccin Mocha",
    category: "Modern Dark",
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    primary: "#89b4fa",
    primaryForeground: "#1e1e2e",
    secondary: "#313244",
    secondaryForeground: "#cdd6f4",
    border: "#45475a",
    cardBg: "#181825",
    cardForeground: "#cdd6f4",
    mutedForeground: "#6c7086",
    accentForeground: "#cdd6f4",
    popoverForeground: "#cdd6f4",
    isDark: true,
  },
  {
    name: "Arc Dark",
    category: "Modern Dark",
    background: "#2f343f",
    foreground: "#d3dae3",
    primary: "#5294e2",
    primaryForeground: "#ffffff",
    secondary: "#383c4a",
    secondaryForeground: "#d3dae3",
    border: "#4b5162",
    cardBg: "#353945",
    cardForeground: "#d3dae3",
    mutedForeground: "#8b9dc3",
    accentForeground: "#d3dae3",
    popoverForeground: "#d3dae3",
    isDark: true,
  },
  {
    name: "Nord Dark",
    category: "Modern Dark",
    background: "#2e3440",
    foreground: "#eceff4",
    primary: "#5e81ac",
    primaryForeground: "#ffffff",
    secondary: "#3b4252",
    secondaryForeground: "#eceff4",
    border: "#434c5e",
    cardBg: "#3b4252",
    cardForeground: "#eceff4",
    mutedForeground: "#81a1c1",
    accentForeground: "#eceff4",
    popoverForeground: "#eceff4",
    isDark: true,
  },
  {
    name: "Gruvbox Dark",
    category: "Modern Dark",
    background: "#282828",
    foreground: "#ebdbb2",
    primary: "#458588",
    primaryForeground: "#ffffff",
    secondary: "#3c3836",
    secondaryForeground: "#ebdbb2",
    border: "#504945",
    cardBg: "#32302f",
    cardForeground: "#ebdbb2",
    mutedForeground: "#a89984",
    accentForeground: "#ebdbb2",
    popoverForeground: "#ebdbb2",
    isDark: true,
  },
  {
    name: "One Dark Pro",
    category: "Modern Dark",
    background: "#21252b",
    foreground: "#abb2bf",
    primary: "#61afef",
    primaryForeground: "#21252b",
    secondary: "#282c34",
    secondaryForeground: "#abb2bf",
    border: "#3e4451",
    cardBg: "#2c313c",
    cardForeground: "#abb2bf",
    mutedForeground: "#5c6370",
    accentForeground: "#abb2bf",
    popoverForeground: "#abb2bf",
    isDark: true,
  },

  // Developer Themes
  {
    name: "VS Code Dark+",
    category: "Developer",
    background: "#1e1e1e",
    foreground: "#d4d4d4",
    primary: "#007acc",
    primaryForeground: "#ffffff",
    secondary: "#2d2d30",
    secondaryForeground: "#d4d4d4",
    border: "#3e3e42",
    cardBg: "#252526",
    cardForeground: "#d4d4d4",
    mutedForeground: "#969696",
    accentForeground: "#d4d4d4",
    popoverForeground: "#d4d4d4",
    isDark: true,
  },
  {
    name: "Dracula",
    category: "Developer",
    background: "#282a36",
    foreground: "#f8f8f2",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    secondary: "#44475a",
    secondaryForeground: "#f8f8f2",
    border: "#6272a4",
    cardBg: "#2d2f3a",
    cardForeground: "#f8f8f2",
    mutedForeground: "#6272a4",
    accentForeground: "#f8f8f2",
    popoverForeground: "#f8f8f2",
    isDark: true,
  },
  {
    name: "Tokyo Night",
    category: "Developer",
    background: "#1a1b26",
    foreground: "#a9b1d6",
    primary: "#7aa2f7",
    primaryForeground: "#1a1b26",
    secondary: "#24283b",
    secondaryForeground: "#a9b1d6",
    border: "#414868",
    cardBg: "#1f2335",
    cardForeground: "#a9b1d6",
    mutedForeground: "#565f89",
    accentForeground: "#a9b1d6",
    popoverForeground: "#a9b1d6",
    isDark: true,
  },
  {
    name: "Monokai Pro",
    category: "Developer",
    background: "#2d2a2e",
    foreground: "#fcfcfa",
    primary: "#ab9df2",
    primaryForeground: "#2d2a2e",
    secondary: "#403e41",
    secondaryForeground: "#fcfcfa",
    border: "#5b595c",
    cardBg: "#363537",
    cardForeground: "#fcfcfa",
    mutedForeground: "#939293",
    accentForeground: "#fcfcfa",
    popoverForeground: "#fcfcfa",
    isDark: true,
  },
  {
    name: "Material Dark",
    category: "Developer",
    background: "#263238",
    foreground: "#eeffff",
    primary: "#82aaff",
    primaryForeground: "#263238",
    secondary: "#2e3c43",
    secondaryForeground: "#eeffff",
    border: "#37474f",
    cardBg: "#37474f",
    cardForeground: "#eeffff",
    mutedForeground: "#546e7a",
    accentForeground: "#eeffff",
    popoverForeground: "#eeffff",
    isDark: true,
  },
  {
    name: "Solarized Dark",
    category: "Developer",
    background: "#002b36",
    foreground: "#839496",
    primary: "#268bd2",
    primaryForeground: "#fdf6e3",
    secondary: "#073642",
    secondaryForeground: "#839496",
    border: "#586e75",
    cardBg: "#073642",
    cardForeground: "#839496",
    mutedForeground: "#657b83",
    accentForeground: "#839496",
    popoverForeground: "#839496",
    isDark: true,
  },
  {
    name: "Palenight",
    category: "Developer",
    background: "#292d3e",
    foreground: "#a6accd",
    primary: "#82b1ff",
    primaryForeground: "#292d3e",
    secondary: "#34324a",
    secondaryForeground: "#a6accd",
    border: "#444267",
    cardBg: "#3a3f58",
    cardForeground: "#a6accd",
    mutedForeground: "#676e95",
    accentForeground: "#a6accd",
    popoverForeground: "#a6accd",
    isDark: true,
  },

  // Modern Light Themes
  {
    name: "GitHub Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#24292f",
    primary: "#0969da",
    primaryForeground: "#ffffff",
    secondary: "#f6f8fa",
    secondaryForeground: "#24292f",
    border: "#d0d7de",
    cardBg: "#f6f8fa",
    cardForeground: "#24292f",
    mutedForeground: "#656d76",
    accentForeground: "#24292f",
    popoverForeground: "#24292f",
    isDark: false,
  },
  {
    name: "Linear Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#5e6ad2",
    primaryForeground: "#ffffff",
    secondary: "#f7f8f9",
    secondaryForeground: "#000000",
    border: "#e1e5e9",
    cardBg: "#fafbfc",
    cardForeground: "#000000",
    mutedForeground: "#6b7280",
    accentForeground: "#000000",
    popoverForeground: "#000000",
    isDark: false,
  },
  {
    name: "Notion Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#37352f",
    primary: "#2eaadc",
    primaryForeground: "#ffffff",
    secondary: "#f7f6f3",
    secondaryForeground: "#37352f",
    border: "#e9e9e7",
    cardBg: "#fbfbfa",
    cardForeground: "#37352f",
    mutedForeground: "#787774",
    accentForeground: "#37352f",
    popoverForeground: "#37352f",
    isDark: false,
  },
  {
    name: "Figma Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#1e1e1e",
    primary: "#0d99ff",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#1e1e1e",
    border: "#e6e6e6",
    cardBg: "#f9f9f9",
    cardForeground: "#1e1e1e",
    mutedForeground: "#666666",
    accentForeground: "#1e1e1e",
    popoverForeground: "#1e1e1e",
    isDark: false,
  },
  {
    name: "Apple Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#1c1c1e",
    primary: "#007aff",
    primaryForeground: "#ffffff",
    secondary: "#f2f2f7",
    secondaryForeground: "#1c1c1e",
    border: "#d1d1d6",
    cardBg: "#f9f9f9",
    cardForeground: "#1c1c1e",
    mutedForeground: "#8e8e93",
    accentForeground: "#1c1c1e",
    popoverForeground: "#1c1c1e",
    isDark: false,
  },
  {
    name: "Tailwind Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#111827",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#f9fafb",
    secondaryForeground: "#111827",
    border: "#e5e7eb",
    cardBg: "#f3f4f6",
    cardForeground: "#111827",
    mutedForeground: "#6b7280",
    accentForeground: "#111827",
    popoverForeground: "#111827",
    isDark: false,
  },
  {
    name: "Vercel Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#0070f3",
    primaryForeground: "#ffffff",
    secondary: "#fafafa",
    secondaryForeground: "#000000",
    border: "#eaeaea",
    cardBg: "#fafafa",
    cardForeground: "#000000",
    mutedForeground: "#666666",
    accentForeground: "#000000",
    popoverForeground: "#000000",
    isDark: false,
  },
  {
    name: "Stripe Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#1a1f36",
    primary: "#635bff",
    primaryForeground: "#ffffff",
    secondary: "#f6f9fc",
    secondaryForeground: "#1a1f36",
    border: "#e3e8ee",
    cardBg: "#f6f9fc",
    cardForeground: "#1a1f36",
    mutedForeground: "#8898aa",
    accentForeground: "#1a1f36",
    popoverForeground: "#1a1f36",
    isDark: false,
  },
  {
    name: "Airbnb Light",
    category: "Modern Light",
    background: "#ffffff",
    foreground: "#222222",
    primary: "#ff5a5f",
    primaryForeground: "#ffffff",
    secondary: "#f7f7f7",
    secondaryForeground: "#222222",
    border: "#dddddd",
    cardBg: "#f7f7f7",
    cardForeground: "#222222",
    mutedForeground: "#717171",
    accentForeground: "#222222",
    popoverForeground: "#222222",
    isDark: false,
  },

  // Soft & Pastel Themes
  {
    name: "Lavender Light",
    category: "Soft & Pastel",
    background: "#fdfbff",
    foreground: "#1c1b1f",
    primary: "#7c4dff",
    primaryForeground: "#ffffff",
    secondary: "#f7f2fa",
    secondaryForeground: "#1c1b1f",
    border: "#e7e0ec",
    cardBg: "#fdf7ff",
    cardForeground: "#1c1b1f",
    mutedForeground: "#79747e",
    accentForeground: "#1c1b1f",
    popoverForeground: "#1c1b1f",
    isDark: false,
  },
  {
    name: "Mint Fresh",
    category: "Soft & Pastel",
    background: "#f0fdf4",
    foreground: "#0f172a",
    primary: "#10b981",
    primaryForeground: "#ffffff",
    secondary: "#dcfce7",
    secondaryForeground: "#0f172a",
    border: "#bbf7d0",
    cardBg: "#ecfdf5",
    cardForeground: "#0f172a",
    mutedForeground: "#6b7280",
    accentForeground: "#0f172a",
    popoverForeground: "#0f172a",
    isDark: false,
  },
  {
    name: "Peach Cream",
    category: "Soft & Pastel",
    background: "#fff7ed",
    foreground: "#1c1917",
    primary: "#ea580c",
    primaryForeground: "#ffffff",
    secondary: "#fed7aa",
    secondaryForeground: "#1c1917",
    border: "#fdba74",
    cardBg: "#ffedd5",
    cardForeground: "#1c1917",
    mutedForeground: "#78716c",
    accentForeground: "#1c1917",
    popoverForeground: "#1c1917",
    isDark: false,
  },
  {
    name: "Sky Blue",
    category: "Soft & Pastel",
    background: "#f0f9ff",
    foreground: "#0c4a6e",
    primary: "#0ea5e9",
    primaryForeground: "#ffffff",
    secondary: "#e0f2fe",
    secondaryForeground: "#0c4a6e",
    border: "#7dd3fc",
    cardBg: "#f0f9ff",
    cardForeground: "#0c4a6e",
    mutedForeground: "#0369a1",
    accentForeground: "#0c4a6e",
    popoverForeground: "#0c4a6e",
    isDark: false,
  },
  {
    name: "Rose Quartz",
    category: "Soft & Pastel",
    background: "#fdf2f8",
    foreground: "#831843",
    primary: "#ec4899",
    primaryForeground: "#ffffff",
    secondary: "#fce7f3",
    secondaryForeground: "#831843",
    border: "#f9a8d4",
    cardBg: "#fef7f0",
    cardForeground: "#831843",
    mutedForeground: "#be185d",
    accentForeground: "#831843",
    popoverForeground: "#831843",
    isDark: false,
  },

  // Minimal Themes
  {
    name: "Pure Dark",
    category: "Minimal",
    background: "#000000",
    foreground: "#ffffff",
    primary: "#ffffff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    border: "#333333",
    cardBg: "#0d0d0d",
    cardForeground: "#ffffff",
    mutedForeground: "#a0a0a0",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "Pure Light",
    category: "Minimal",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#000000",
    primaryForeground: "#ffffff",
    secondary: "#f8f8f8",
    secondaryForeground: "#000000",
    border: "#e0e0e0",
    cardBg: "#fcfcfc",
    cardForeground: "#000000",
    mutedForeground: "#666666",
    accentForeground: "#000000",
    popoverForeground: "#000000",
    isDark: false,
  },
  {
    name: "Monospace Dark",
    category: "Minimal",
    background: "#0a0a0a",
    foreground: "#f5f5f5",
    primary: "#00ff00",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#f5f5f5",
    border: "#2a2a2a",
    cardBg: "#121212",
    cardForeground: "#f5f5f5",
    mutedForeground: "#888888",
    accentForeground: "#f5f5f5",
    popoverForeground: "#f5f5f5",
    isDark: true,
  },
  {
    name: "Paper",
    category: "Minimal",
    background: "#fefefe",
    foreground: "#2a2a2a",
    primary: "#4a5568",
    primaryForeground: "#ffffff",
    secondary: "#f7f7f7",
    secondaryForeground: "#2a2a2a",
    border: "#e2e8f0",
    cardBg: "#fdfdfd",
    cardForeground: "#2a2a2a",
    mutedForeground: "#718096",
    accentForeground: "#2a2a2a",
    popoverForeground: "#2a2a2a",
    isDark: false,
  },
  {
    name: "Ink",
    category: "Minimal",
    background: "#0f0f0f",
    foreground: "#f0f0f0",
    primary: "#f0f0f0",
    primaryForeground: "#0f0f0f",
    secondary: "#1f1f1f",
    secondaryForeground: "#f0f0f0",
    border: "#2f2f2f",
    cardBg: "#181818",
    cardForeground: "#f0f0f0",
    mutedForeground: "#a0a0a0",
    accentForeground: "#f0f0f0",
    popoverForeground: "#f0f0f0",
    isDark: true,
  },

  // Focus Themes
  {
    name: "Deep Focus",
    category: "Focus",
    background: "#1a1a1a",
    foreground: "#e8e8e8",
    primary: "#4a9eff",
    primaryForeground: "#ffffff",
    secondary: "#2a2a2a",
    secondaryForeground: "#e8e8e8",
    border: "#3a3a3a",
    cardBg: "#222222",
    cardForeground: "#e8e8e8",
    mutedForeground: "#999999",
    accentForeground: "#e8e8e8",
    popoverForeground: "#e8e8e8",
    isDark: true,
  },
  {
    name: "Zen Mode",
    category: "Focus",
    background: "#f8f9fa",
    foreground: "#2d3748",
    primary: "#4299e1",
    primaryForeground: "#ffffff",
    secondary: "#edf2f7",
    secondaryForeground: "#2d3748",
    border: "#e2e8f0",
    cardBg: "#ffffff",
    cardForeground: "#2d3748",
    mutedForeground: "#718096",
    accentForeground: "#2d3748",
    popoverForeground: "#2d3748",
    isDark: false,
  },
  {
    name: "Reading Mode",
    category: "Focus",
    background: "#faf7f2",
    foreground: "#3e2723",
    primary: "#8d6e63",
    primaryForeground: "#ffffff",
    secondary: "#f5f5dc",
    secondaryForeground: "#3e2723",
    border: "#d7ccc8",
    cardBg: "#ffffff",
    cardForeground: "#3e2723",
    mutedForeground: "#6d4c41",
    accentForeground: "#3e2723",
    popoverForeground: "#3e2723",
    isDark: false,
  },
  {
    name: "Night Reader",
    category: "Focus",
    background: "#1c1c1c",
    foreground: "#e0d5c7",
    primary: "#d4a574",
    primaryForeground: "#1c1c1c",
    secondary: "#2a2a2a",
    secondaryForeground: "#e0d5c7",
    border: "#3a3a3a",
    cardBg: "#242424",
    cardForeground: "#e0d5c7",
    mutedForeground: "#b39c7a",
    accentForeground: "#e0d5c7",
    popoverForeground: "#e0d5c7",
    isDark: true,
  },

  // High Contrast
  {
    name: "High Contrast Dark",
    category: "High Contrast",
    background: "#000000",
    foreground: "#ffffff",
    primary: "#00ffff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    border: "#666666",
    cardBg: "#0a0a0a",
    cardForeground: "#ffffff",
    mutedForeground: "#cccccc",
    accentForeground: "#ffffff",
    popoverForeground: "#ffffff",
    isDark: true,
  },
  {
    name: "High Contrast Light",
    category: "High Contrast",
    background: "#ffffff",
    foreground: "#000000",
    primary: "#0000ff",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#000000",
    border: "#888888",
    cardBg: "#f8f8f8",
    cardForeground: "#000000",
    mutedForeground: "#333333",
    accentForeground: "#000000",
    popoverForeground: "#000000",
    isDark: false,
  },

  // Nature & Calm
  {
    name: "Forest Night",
    category: "Nature",
    background: "#1b2b1b",
    foreground: "#e8f5e8",
    primary: "#4ade80",
    primaryForeground: "#000000",
    secondary: "#2a3b2a",
    secondaryForeground: "#e8f5e8",
    border: "#3a4b3a",
    cardBg: "#1f2e1f",
    cardForeground: "#e8f5e8",
    mutedForeground: "#94a3b8",
    accentForeground: "#e8f5e8",
    popoverForeground: "#e8f5e8",
    isDark: true,
  },
  {
    name: "Ocean Blue",
    category: "Nature",
    background: "#1e2a3a",
    foreground: "#e0f2fe",
    primary: "#38bdf8",
    primaryForeground: "#ffffff",
    secondary: "#2a3b4a",
    secondaryForeground: "#e0f2fe",
    border: "#3a4b5a",
    cardBg: "#243240",
    cardForeground: "#e0f2fe",
    mutedForeground: "#94a3b8",
    accentForeground: "#e0f2fe",
    popoverForeground: "#e0f2fe",
    isDark: true,
  },
  {
    name: "Sunset Warm",
    category: "Warm",
    background: "#2a1f1f",
    foreground: "#fef2e8",
    primary: "#fb923c",
    primaryForeground: "#ffffff",
    secondary: "#3a2a2a",
    secondaryForeground: "#fef2e8",
    border: "#4a3a3a",
    cardBg: "#322727",
    cardForeground: "#fef2e8",
    mutedForeground: "#d1d5db",
    accentForeground: "#fef2e8",
    popoverForeground: "#fef2e8",
    isDark: true,
  },
  {
    name: "Mountain Mist",
    category: "Nature",
    background: "#f8fafc",
    foreground: "#334155",
    primary: "#0f766e",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#334155",
    border: "#cbd5e1",
    cardBg: "#ffffff",
    cardForeground: "#334155",
    mutedForeground: "#64748b",
    accentForeground: "#334155",
    popoverForeground: "#334155",
    isDark: false,
  },
  {
    name: "Desert Sand",
    category: "Warm",
    background: "#faf5f0",
    foreground: "#78350f",
    primary: "#ea580c",
    primaryForeground: "#ffffff",
    secondary: "#fef7ed",
    secondaryForeground: "#78350f",
    border: "#fed7aa",
    cardBg: "#fffbeb",
    cardForeground: "#78350f",
    mutedForeground: "#a16207",
    accentForeground: "#78350f",
    popoverForeground: "#78350f",
    isDark: false,
  },

  // Creative & Unique
  {
    name: "Cyberpunk",
    category: "Creative",
    background: "#0a0e27",
    foreground: "#00ffff",
    primary: "#ff00ff",
    primaryForeground: "#000000",
    secondary: "#1a1a3a",
    secondaryForeground: "#00ffff",
    border: "#ff00ff",
    cardBg: "#0f1430",
    cardForeground: "#00ffff",
    mutedForeground: "#8a8aff",
    accentForeground: "#00ffff",
    popoverForeground: "#00ffff",
    isDark: true,
  },
  {
    name: "Retro Wave",
    category: "Creative",
    background: "#1a0b2e",
    foreground: "#ff6ec7",
    primary: "#00f5ff",
    primaryForeground: "#1a0b2e",
    secondary: "#2d1b3d",
    secondaryForeground: "#ff6ec7",
    border: "#7209b7",
    cardBg: "#1f1035",
    cardForeground: "#ff6ec7",
    mutedForeground: "#ca6fc1",
    accentForeground: "#ff6ec7",
    popoverForeground: "#ff6ec7",
    isDark: true,
  },
  {
    name: "Neon Green",
    category: "Creative",
    background: "#0d1421",
    foreground: "#39ff14",
    primary: "#39ff14",
    primaryForeground: "#000000",
    secondary: "#1a2332",
    secondaryForeground: "#39ff14",
    border: "#2d4a22",
    cardBg: "#111926",
    cardForeground: "#39ff14",
    mutedForeground: "#29cc0a",
    accentForeground: "#39ff14",
    popoverForeground: "#39ff14",
    isDark: true,
  },
  {
    name: "Amber Glow",
    category: "Creative",
    background: "#1a1308",
    foreground: "#ffb000",
    primary: "#ff8c00",
    primaryForeground: "#000000",
    secondary: "#2a2010",
    secondaryForeground: "#ffb000",
    border: "#4a3618",
    cardBg: "#1f1a0d",
    cardForeground: "#ffb000",
    mutedForeground: "#cc8800",
    accentForeground: "#ffb000",
    popoverForeground: "#ffb000",
    isDark: true,
  },
] as const;

export const themeCategories = [
  {
    name: "Modern Dark",
    icon: "🌙",
    description: "Contemporary dark themes with excellent readability",
  },
  {
    name: "Modern Light",
    icon: "☀️",
    description: "Clean, modern light themes for focused work",
  },
  {
    name: "Developer",
    icon: "💻",
    description: "Code editor inspired themes with perfect contrast",
  },
  {
    name: "Minimal",
    icon: "⚪",
    description: "Distraction-free themes for maximum focus",
  },
  {
    name: "Focus",
    icon: "🎯",
    description: "Specially designed for deep work and concentration",
  },
  {
    name: "High Contrast",
    icon: "⚫",
    description: "Maximum contrast for accessibility and clarity",
  },
  {
    name: "Nature",
    icon: "🌿",
    description: "Calming nature-inspired color palettes",
  },
  {
    name: "Warm",
    icon: "🔥",
    description: "Cozy, warm-toned themes for comfortable reading",
  },
  {
    name: "Soft & Pastel",
    icon: "🌸",
    description: "Gentle, easy-on-the-eyes color schemes",
  },
  {
    name: "Creative",
    icon: "🎨",
    description: "Bold and artistic themes for creative expression",
  },
] as const;

export type ThemeCategory = (typeof themeCategories)[number]["name"];
