import { v4 as uuidv4 } from "uuid";

export const union = <T>(a: T[], b: T[]): T[] => {
  const arrSet = new Set([...a, ...b]);
  return Array.from(arrSet);
};

/**
 * Generates an array of unique IDs
 *
 * This function creates an array of a specified length, populating each
 * element with a unique identifier generated by the uuidv4 function.
 *
 */
export const generateArrayWithUniqueIds = (length: number) => {
  return Array.from({ length }, () => uuidv4());
};
